// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow_serving/apis/input.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "tensorflow_serving/apis/input.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace tensorflow {
namespace serving {

namespace {

const ::google::protobuf::Descriptor* ExampleList_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ExampleList_reflection_ = NULL;
const ::google::protobuf::Descriptor* ExampleListWithContext_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  ExampleListWithContext_reflection_ = NULL;
const ::google::protobuf::Descriptor* Input_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Input_reflection_ = NULL;
struct InputOneofInstance {
  const ::tensorflow::serving::ExampleList* example_list_;
  const ::tensorflow::serving::ExampleListWithContext* example_list_with_context_;
}* Input_default_oneof_instance_ = NULL;

}  // namespace


void protobuf_AssignDesc_tensorflow_5fserving_2fapis_2finput_2eproto() GOOGLE_ATTRIBUTE_COLD;
void protobuf_AssignDesc_tensorflow_5fserving_2fapis_2finput_2eproto() {
  protobuf_AddDesc_tensorflow_5fserving_2fapis_2finput_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "tensorflow_serving/apis/input.proto");
  GOOGLE_CHECK(file != NULL);
  ExampleList_descriptor_ = file->message_type(0);
  static const int ExampleList_offsets_[1] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExampleList, examples_),
  };
  ExampleList_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ExampleList_descriptor_,
      ExampleList::internal_default_instance(),
      ExampleList_offsets_,
      -1,
      -1,
      -1,
      sizeof(ExampleList),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExampleList, _internal_metadata_));
  ExampleListWithContext_descriptor_ = file->message_type(1);
  static const int ExampleListWithContext_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExampleListWithContext, examples_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExampleListWithContext, context_),
  };
  ExampleListWithContext_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      ExampleListWithContext_descriptor_,
      ExampleListWithContext::internal_default_instance(),
      ExampleListWithContext_offsets_,
      -1,
      -1,
      -1,
      sizeof(ExampleListWithContext),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(ExampleListWithContext, _internal_metadata_));
  Input_descriptor_ = file->message_type(2);
  static const int Input_offsets_[3] = {
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(Input_default_oneof_instance_, example_list_),
    PROTO2_GENERATED_DEFAULT_ONEOF_FIELD_OFFSET(Input_default_oneof_instance_, example_list_with_context_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Input, kind_),
  };
  Input_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Input_descriptor_,
      Input::internal_default_instance(),
      Input_offsets_,
      -1,
      -1,
      -1,
      Input_default_oneof_instance_,
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Input, _oneof_case_[0]),
      sizeof(Input),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Input, _internal_metadata_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_tensorflow_5fserving_2fapis_2finput_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) GOOGLE_ATTRIBUTE_COLD;
void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ExampleList_descriptor_, ExampleList::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      ExampleListWithContext_descriptor_, ExampleListWithContext::internal_default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Input_descriptor_, Input::internal_default_instance());
}

}  // namespace

void protobuf_ShutdownFile_tensorflow_5fserving_2fapis_2finput_2eproto() {
  ExampleList_default_instance_.Shutdown();
  delete ExampleList_reflection_;
  ExampleListWithContext_default_instance_.Shutdown();
  delete ExampleListWithContext_reflection_;
  Input_default_instance_.Shutdown();
  delete Input_default_oneof_instance_;
  delete Input_reflection_;
}

void protobuf_InitDefaults_tensorflow_5fserving_2fapis_2finput_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::tensorflow::protobuf_InitDefaults_tensorflow_2fcore_2fexample_2fexample_2eproto();
  ExampleList_default_instance_.DefaultConstruct();
  ExampleListWithContext_default_instance_.DefaultConstruct();
  Input_default_instance_.DefaultConstruct();
  Input_default_oneof_instance_ = new InputOneofInstance();
  ExampleList_default_instance_.get_mutable()->InitAsDefaultInstance();
  ExampleListWithContext_default_instance_.get_mutable()->InitAsDefaultInstance();
  Input_default_instance_.get_mutable()->InitAsDefaultInstance();
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_InitDefaults_tensorflow_5fserving_2fapis_2finput_2eproto_once_);
void protobuf_InitDefaults_tensorflow_5fserving_2fapis_2finput_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_InitDefaults_tensorflow_5fserving_2fapis_2finput_2eproto_once_,
                 &protobuf_InitDefaults_tensorflow_5fserving_2fapis_2finput_2eproto_impl);
}
void protobuf_AddDesc_tensorflow_5fserving_2fapis_2finput_2eproto_impl() {
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  protobuf_InitDefaults_tensorflow_5fserving_2fapis_2finput_2eproto();
  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n#tensorflow_serving/apis/input.proto\022\022t"
    "ensorflow.serving\032%tensorflow/core/examp"
    "le/example.proto\"4\n\013ExampleList\022%\n\010examp"
    "les\030\001 \003(\0132\023.tensorflow.Example\"e\n\026Exampl"
    "eListWithContext\022%\n\010examples\030\001 \003(\0132\023.ten"
    "sorflow.Example\022$\n\007context\030\002 \001(\0132\023.tenso"
    "rflow.Example\"\231\001\n\005Input\0227\n\014example_list\030"
    "\001 \001(\0132\037.tensorflow.serving.ExampleListH\000"
    "\022O\n\031example_list_with_context\030\002 \001(\0132*.te"
    "nsorflow.serving.ExampleListWithContextH"
    "\000B\006\n\004kindB\003\370\001\001b\006proto3", 422);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "tensorflow_serving/apis/input.proto", &protobuf_RegisterTypes);
  ::tensorflow::protobuf_AddDesc_tensorflow_2fcore_2fexample_2fexample_2eproto();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_tensorflow_5fserving_2fapis_2finput_2eproto);
}

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AddDesc_tensorflow_5fserving_2fapis_2finput_2eproto_once_);
void protobuf_AddDesc_tensorflow_5fserving_2fapis_2finput_2eproto() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AddDesc_tensorflow_5fserving_2fapis_2finput_2eproto_once_,
                 &protobuf_AddDesc_tensorflow_5fserving_2fapis_2finput_2eproto_impl);
}
// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_tensorflow_5fserving_2fapis_2finput_2eproto {
  StaticDescriptorInitializer_tensorflow_5fserving_2fapis_2finput_2eproto() {
    protobuf_AddDesc_tensorflow_5fserving_2fapis_2finput_2eproto();
  }
} static_descriptor_initializer_tensorflow_5fserving_2fapis_2finput_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD GOOGLE_ATTRIBUTE_NORETURN;
static void MergeFromFail(int line) {
  ::google::protobuf::internal::MergeFromFail(__FILE__, line);
}

}  // namespace


// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ExampleList::kExamplesFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ExampleList::ExampleList()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_tensorflow_5fserving_2fapis_2finput_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.serving.ExampleList)
}
ExampleList::ExampleList(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena),
  examples_(arena) {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_InitDefaults_tensorflow_5fserving_2fapis_2finput_2eproto();
#endif  // GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorflow.serving.ExampleList)
}

void ExampleList::InitAsDefaultInstance() {
}

ExampleList::ExampleList(const ExampleList& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:tensorflow.serving.ExampleList)
}

void ExampleList::SharedCtor() {
  _cached_size_ = 0;
}

ExampleList::~ExampleList() {
  // @@protoc_insertion_point(destructor:tensorflow.serving.ExampleList)
  SharedDtor();
}

void ExampleList::SharedDtor() {
  ::google::protobuf::Arena* arena = GetArenaNoVirtual();
  if (arena != NULL) {
    return;
  }

}

void ExampleList::ArenaDtor(void* object) {
  ExampleList* _this = reinterpret_cast< ExampleList* >(object);
  (void)_this;
}
void ExampleList::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void ExampleList::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ExampleList::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ExampleList_descriptor_;
}

const ExampleList& ExampleList::default_instance() {
  protobuf_InitDefaults_tensorflow_5fserving_2fapis_2finput_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<ExampleList> ExampleList_default_instance_;

ExampleList* ExampleList::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<ExampleList>(arena);
}

void ExampleList::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.serving.ExampleList)
  examples_.Clear();
}

bool ExampleList::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tensorflow.serving.ExampleList)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .tensorflow.Example examples = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_examples:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_examples()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_examples;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tensorflow.serving.ExampleList)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tensorflow.serving.ExampleList)
  return false;
#undef DO_
}

void ExampleList::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tensorflow.serving.ExampleList)
  // repeated .tensorflow.Example examples = 1;
  for (unsigned int i = 0, n = this->examples_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->examples(i), output);
  }

  // @@protoc_insertion_point(serialize_end:tensorflow.serving.ExampleList)
}

::google::protobuf::uint8* ExampleList::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.serving.ExampleList)
  // repeated .tensorflow.Example examples = 1;
  for (unsigned int i = 0, n = this->examples_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->examples(i), false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.serving.ExampleList)
  return target;
}

size_t ExampleList::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorflow.serving.ExampleList)
  size_t total_size = 0;

  // repeated .tensorflow.Example examples = 1;
  {
    unsigned int count = this->examples_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->examples(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ExampleList::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tensorflow.serving.ExampleList)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const ExampleList* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ExampleList>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tensorflow.serving.ExampleList)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tensorflow.serving.ExampleList)
    UnsafeMergeFrom(*source);
  }
}

void ExampleList::MergeFrom(const ExampleList& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.serving.ExampleList)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void ExampleList::UnsafeMergeFrom(const ExampleList& from) {
  GOOGLE_DCHECK(&from != this);
  examples_.MergeFrom(from.examples_);
}

void ExampleList::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tensorflow.serving.ExampleList)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExampleList::CopyFrom(const ExampleList& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.serving.ExampleList)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool ExampleList::IsInitialized() const {

  return true;
}

void ExampleList::Swap(ExampleList* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    ExampleList temp;
    temp.UnsafeMergeFrom(*this);
    CopyFrom(*other);
    other->CopyFrom(temp);
  }
}
void ExampleList::UnsafeArenaSwap(ExampleList* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void ExampleList::InternalSwap(ExampleList* other) {
  examples_.UnsafeArenaSwap(&other->examples_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ExampleList::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ExampleList_descriptor_;
  metadata.reflection = ExampleList_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ExampleList

// repeated .tensorflow.Example examples = 1;
int ExampleList::examples_size() const {
  return examples_.size();
}
void ExampleList::clear_examples() {
  examples_.Clear();
}
const ::tensorflow::Example& ExampleList::examples(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.ExampleList.examples)
  return examples_.Get(index);
}
::tensorflow::Example* ExampleList::mutable_examples(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.ExampleList.examples)
  return examples_.Mutable(index);
}
::tensorflow::Example* ExampleList::add_examples() {
  // @@protoc_insertion_point(field_add:tensorflow.serving.ExampleList.examples)
  return examples_.Add();
}
::google::protobuf::RepeatedPtrField< ::tensorflow::Example >*
ExampleList::mutable_examples() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.serving.ExampleList.examples)
  return &examples_;
}
const ::google::protobuf::RepeatedPtrField< ::tensorflow::Example >&
ExampleList::examples() const {
  // @@protoc_insertion_point(field_list:tensorflow.serving.ExampleList.examples)
  return examples_;
}

inline const ExampleList* ExampleList::internal_default_instance() {
  return &ExampleList_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

void ExampleListWithContext::_slow_mutable_context() {
  context_ = ::google::protobuf::Arena::CreateMessage< ::tensorflow::Example >(
      GetArenaNoVirtual());
}
::tensorflow::Example* ExampleListWithContext::_slow_release_context() {
  if (context_ == NULL) {
    return NULL;
  } else {
    ::tensorflow::Example* temp = new ::tensorflow::Example(*context_);
    context_ = NULL;
    return temp;
  }
}
::tensorflow::Example* ExampleListWithContext::unsafe_arena_release_context() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tensorflow.serving.ExampleListWithContext.context)
  
  ::tensorflow::Example* temp = context_;
  context_ = NULL;
  return temp;
}
void ExampleListWithContext::_slow_set_allocated_context(
    ::google::protobuf::Arena* message_arena, ::tensorflow::Example** context) {
    if (message_arena != NULL && 
        ::google::protobuf::Arena::GetArena(*context) == NULL) {
      message_arena->Own(*context);
    } else if (message_arena !=
               ::google::protobuf::Arena::GetArena(*context)) {
      ::tensorflow::Example* new_context = 
            ::google::protobuf::Arena::CreateMessage< ::tensorflow::Example >(
            message_arena);
      new_context->CopyFrom(**context);
      *context = new_context;
    }
}
void ExampleListWithContext::unsafe_arena_set_allocated_context(
    ::tensorflow::Example* context) {
  if (GetArenaNoVirtual() == NULL) {
    delete context_;
  }
  context_ = context;
  if (context) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.ExampleListWithContext.context)
}
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int ExampleListWithContext::kExamplesFieldNumber;
const int ExampleListWithContext::kContextFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

ExampleListWithContext::ExampleListWithContext()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_tensorflow_5fserving_2fapis_2finput_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.serving.ExampleListWithContext)
}
ExampleListWithContext::ExampleListWithContext(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena),
  examples_(arena) {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_InitDefaults_tensorflow_5fserving_2fapis_2finput_2eproto();
#endif  // GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorflow.serving.ExampleListWithContext)
}

void ExampleListWithContext::InitAsDefaultInstance() {
  context_ = const_cast< ::tensorflow::Example*>(
      ::tensorflow::Example::internal_default_instance());
}

ExampleListWithContext::ExampleListWithContext(const ExampleListWithContext& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:tensorflow.serving.ExampleListWithContext)
}

void ExampleListWithContext::SharedCtor() {
  context_ = NULL;
  _cached_size_ = 0;
}

ExampleListWithContext::~ExampleListWithContext() {
  // @@protoc_insertion_point(destructor:tensorflow.serving.ExampleListWithContext)
  SharedDtor();
}

void ExampleListWithContext::SharedDtor() {
  ::google::protobuf::Arena* arena = GetArenaNoVirtual();
  if (arena != NULL) {
    return;
  }

  if (this != &ExampleListWithContext_default_instance_.get()) {
    delete context_;
  }
}

void ExampleListWithContext::ArenaDtor(void* object) {
  ExampleListWithContext* _this = reinterpret_cast< ExampleListWithContext* >(object);
  (void)_this;
}
void ExampleListWithContext::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void ExampleListWithContext::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* ExampleListWithContext::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return ExampleListWithContext_descriptor_;
}

const ExampleListWithContext& ExampleListWithContext::default_instance() {
  protobuf_InitDefaults_tensorflow_5fserving_2fapis_2finput_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<ExampleListWithContext> ExampleListWithContext_default_instance_;

ExampleListWithContext* ExampleListWithContext::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<ExampleListWithContext>(arena);
}

void ExampleListWithContext::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.serving.ExampleListWithContext)
  if (GetArenaNoVirtual() == NULL && context_ != NULL) delete context_;
  context_ = NULL;
  examples_.Clear();
}

bool ExampleListWithContext::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tensorflow.serving.ExampleListWithContext)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // repeated .tensorflow.Example examples = 1;
      case 1: {
        if (tag == 10) {
          DO_(input->IncrementRecursionDepth());
         parse_loop_examples:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtualNoRecursionDepth(
                input, add_examples()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(10)) goto parse_loop_examples;
        input->UnsafeDecrementRecursionDepth();
        if (input->ExpectTag(18)) goto parse_context;
        break;
      }

      // optional .tensorflow.Example context = 2;
      case 2: {
        if (tag == 18) {
         parse_context:
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_context()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tensorflow.serving.ExampleListWithContext)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tensorflow.serving.ExampleListWithContext)
  return false;
#undef DO_
}

void ExampleListWithContext::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tensorflow.serving.ExampleListWithContext)
  // repeated .tensorflow.Example examples = 1;
  for (unsigned int i = 0, n = this->examples_size(); i < n; i++) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, this->examples(i), output);
  }

  // optional .tensorflow.Example context = 2;
  if (this->has_context()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *this->context_, output);
  }

  // @@protoc_insertion_point(serialize_end:tensorflow.serving.ExampleListWithContext)
}

::google::protobuf::uint8* ExampleListWithContext::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.serving.ExampleListWithContext)
  // repeated .tensorflow.Example examples = 1;
  for (unsigned int i = 0, n = this->examples_size(); i < n; i++) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, this->examples(i), false, target);
  }

  // optional .tensorflow.Example context = 2;
  if (this->has_context()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *this->context_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.serving.ExampleListWithContext)
  return target;
}

size_t ExampleListWithContext::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorflow.serving.ExampleListWithContext)
  size_t total_size = 0;

  // optional .tensorflow.Example context = 2;
  if (this->has_context()) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
        *this->context_);
  }

  // repeated .tensorflow.Example examples = 1;
  {
    unsigned int count = this->examples_size();
    total_size += 1UL * count;
    for (unsigned int i = 0; i < count; i++) {
      total_size +=
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          this->examples(i));
    }
  }

  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void ExampleListWithContext::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tensorflow.serving.ExampleListWithContext)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const ExampleListWithContext* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const ExampleListWithContext>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tensorflow.serving.ExampleListWithContext)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tensorflow.serving.ExampleListWithContext)
    UnsafeMergeFrom(*source);
  }
}

void ExampleListWithContext::MergeFrom(const ExampleListWithContext& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.serving.ExampleListWithContext)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void ExampleListWithContext::UnsafeMergeFrom(const ExampleListWithContext& from) {
  GOOGLE_DCHECK(&from != this);
  examples_.MergeFrom(from.examples_);
  if (from.has_context()) {
    mutable_context()->::tensorflow::Example::MergeFrom(from.context());
  }
}

void ExampleListWithContext::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tensorflow.serving.ExampleListWithContext)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void ExampleListWithContext::CopyFrom(const ExampleListWithContext& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.serving.ExampleListWithContext)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool ExampleListWithContext::IsInitialized() const {

  return true;
}

void ExampleListWithContext::Swap(ExampleListWithContext* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    ExampleListWithContext temp;
    temp.UnsafeMergeFrom(*this);
    CopyFrom(*other);
    other->CopyFrom(temp);
  }
}
void ExampleListWithContext::UnsafeArenaSwap(ExampleListWithContext* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void ExampleListWithContext::InternalSwap(ExampleListWithContext* other) {
  examples_.UnsafeArenaSwap(&other->examples_);
  std::swap(context_, other->context_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata ExampleListWithContext::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = ExampleListWithContext_descriptor_;
  metadata.reflection = ExampleListWithContext_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// ExampleListWithContext

// repeated .tensorflow.Example examples = 1;
int ExampleListWithContext::examples_size() const {
  return examples_.size();
}
void ExampleListWithContext::clear_examples() {
  examples_.Clear();
}
const ::tensorflow::Example& ExampleListWithContext::examples(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.ExampleListWithContext.examples)
  return examples_.Get(index);
}
::tensorflow::Example* ExampleListWithContext::mutable_examples(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.ExampleListWithContext.examples)
  return examples_.Mutable(index);
}
::tensorflow::Example* ExampleListWithContext::add_examples() {
  // @@protoc_insertion_point(field_add:tensorflow.serving.ExampleListWithContext.examples)
  return examples_.Add();
}
::google::protobuf::RepeatedPtrField< ::tensorflow::Example >*
ExampleListWithContext::mutable_examples() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.serving.ExampleListWithContext.examples)
  return &examples_;
}
const ::google::protobuf::RepeatedPtrField< ::tensorflow::Example >&
ExampleListWithContext::examples() const {
  // @@protoc_insertion_point(field_list:tensorflow.serving.ExampleListWithContext.examples)
  return examples_;
}

// optional .tensorflow.Example context = 2;
bool ExampleListWithContext::has_context() const {
  return this != internal_default_instance() && context_ != NULL;
}
void ExampleListWithContext::clear_context() {
  if (GetArenaNoVirtual() == NULL && context_ != NULL) delete context_;
  context_ = NULL;
}
const ::tensorflow::Example& ExampleListWithContext::context() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.ExampleListWithContext.context)
  return context_ != NULL ? *context_
                         : *::tensorflow::Example::internal_default_instance();
}
::tensorflow::Example* ExampleListWithContext::mutable_context() {
  
  if (context_ == NULL) {
    _slow_mutable_context();
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.ExampleListWithContext.context)
  return context_;
}
::tensorflow::Example* ExampleListWithContext::release_context() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.ExampleListWithContext.context)
  
  if (GetArenaNoVirtual() != NULL) {
    return _slow_release_context();
  } else {
    ::tensorflow::Example* temp = context_;
    context_ = NULL;
    return temp;
  }
}
 void ExampleListWithContext::set_allocated_context(::tensorflow::Example* context) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete context_;
  }
  if (context != NULL) {
    _slow_set_allocated_context(message_arena, &context);
  }
  context_ = context;
  if (context) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.ExampleListWithContext.context)
}

inline const ExampleListWithContext* ExampleListWithContext::internal_default_instance() {
  return &ExampleListWithContext_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Input::kExampleListFieldNumber;
const int Input::kExampleListWithContextFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Input::Input()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  if (this != internal_default_instance()) protobuf_InitDefaults_tensorflow_5fserving_2fapis_2finput_2eproto();
  SharedCtor();
  // @@protoc_insertion_point(constructor:tensorflow.serving.Input)
}
Input::Input(::google::protobuf::Arena* arena)
  : ::google::protobuf::Message(),
  _internal_metadata_(arena) {
#ifdef GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  protobuf_InitDefaults_tensorflow_5fserving_2fapis_2finput_2eproto();
#endif  // GOOGLE_PROTOBUF_NO_STATIC_INITIALIZER
  SharedCtor();
  RegisterArenaDtor(arena);
  // @@protoc_insertion_point(arena_constructor:tensorflow.serving.Input)
}

void Input::InitAsDefaultInstance() {
  Input_default_oneof_instance_->example_list_ = const_cast< ::tensorflow::serving::ExampleList*>(
      ::tensorflow::serving::ExampleList::internal_default_instance());
  Input_default_oneof_instance_->example_list_with_context_ = const_cast< ::tensorflow::serving::ExampleListWithContext*>(
      ::tensorflow::serving::ExampleListWithContext::internal_default_instance());
}

Input::Input(const Input& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  UnsafeMergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:tensorflow.serving.Input)
}

void Input::SharedCtor() {
  clear_has_kind();
  _cached_size_ = 0;
}

Input::~Input() {
  // @@protoc_insertion_point(destructor:tensorflow.serving.Input)
  SharedDtor();
}

void Input::SharedDtor() {
  ::google::protobuf::Arena* arena = GetArenaNoVirtual();
  if (arena != NULL) {
    return;
  }

  if (has_kind()) {
    clear_kind();
  }
}

void Input::ArenaDtor(void* object) {
  Input* _this = reinterpret_cast< Input* >(object);
  (void)_this;
}
void Input::RegisterArenaDtor(::google::protobuf::Arena* arena) {
}
void Input::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Input::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Input_descriptor_;
}

const Input& Input::default_instance() {
  protobuf_InitDefaults_tensorflow_5fserving_2fapis_2finput_2eproto();
  return *internal_default_instance();
}

::google::protobuf::internal::ExplicitlyConstructed<Input> Input_default_instance_;

Input* Input::New(::google::protobuf::Arena* arena) const {
  return ::google::protobuf::Arena::CreateMessage<Input>(arena);
}

void Input::clear_kind() {
// @@protoc_insertion_point(one_of_clear_start:tensorflow.serving.Input)
  switch (kind_case()) {
    case kExampleList: {
      if (GetArenaNoVirtual() == NULL) {
        delete kind_.example_list_;
      }
      break;
    }
    case kExampleListWithContext: {
      if (GetArenaNoVirtual() == NULL) {
        delete kind_.example_list_with_context_;
      }
      break;
    }
    case KIND_NOT_SET: {
      break;
    }
  }
  _oneof_case_[0] = KIND_NOT_SET;
}


void Input::Clear() {
// @@protoc_insertion_point(message_clear_start:tensorflow.serving.Input)
  clear_kind();
}

bool Input::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:tensorflow.serving.Input)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .tensorflow.serving.ExampleList example_list = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_example_list()));
        } else {
          goto handle_unusual;
        }
        goto after_example_list_with_context;
        break;
      }

      // optional .tensorflow.serving.ExampleListWithContext example_list_with_context = 2;
      case 2: {
        if (tag == 18) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadMessageNoVirtual(
               input, mutable_example_list_with_context()));
        } else {
          goto handle_unusual;
        }
       after_example_list_with_context:
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:tensorflow.serving.Input)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:tensorflow.serving.Input)
  return false;
#undef DO_
}

void Input::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:tensorflow.serving.Input)
  // optional .tensorflow.serving.ExampleList example_list = 1;
  if (has_example_list()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      1, *kind_.example_list_, output);
  }

  // optional .tensorflow.serving.ExampleListWithContext example_list_with_context = 2;
  if (has_example_list_with_context()) {
    ::google::protobuf::internal::WireFormatLite::WriteMessageMaybeToArray(
      2, *kind_.example_list_with_context_, output);
  }

  // @@protoc_insertion_point(serialize_end:tensorflow.serving.Input)
}

::google::protobuf::uint8* Input::InternalSerializeWithCachedSizesToArray(
    bool deterministic, ::google::protobuf::uint8* target) const {
  (void)deterministic; // Unused
  // @@protoc_insertion_point(serialize_to_array_start:tensorflow.serving.Input)
  // optional .tensorflow.serving.ExampleList example_list = 1;
  if (has_example_list()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        1, *kind_.example_list_, false, target);
  }

  // optional .tensorflow.serving.ExampleListWithContext example_list_with_context = 2;
  if (has_example_list_with_context()) {
    target = ::google::protobuf::internal::WireFormatLite::
      InternalWriteMessageNoVirtualToArray(
        2, *kind_.example_list_with_context_, false, target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:tensorflow.serving.Input)
  return target;
}

size_t Input::ByteSizeLong() const {
// @@protoc_insertion_point(message_byte_size_start:tensorflow.serving.Input)
  size_t total_size = 0;

  switch (kind_case()) {
    // optional .tensorflow.serving.ExampleList example_list = 1;
    case kExampleList: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *kind_.example_list_);
      break;
    }
    // optional .tensorflow.serving.ExampleListWithContext example_list_with_context = 2;
    case kExampleListWithContext: {
      total_size += 1 +
        ::google::protobuf::internal::WireFormatLite::MessageSizeNoVirtual(
          *kind_.example_list_with_context_);
      break;
    }
    case KIND_NOT_SET: {
      break;
    }
  }
  int cached_size = ::google::protobuf::internal::ToCachedSize(total_size);
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = cached_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Input::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:tensorflow.serving.Input)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Input* source =
      ::google::protobuf::internal::DynamicCastToGenerated<const Input>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:tensorflow.serving.Input)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:tensorflow.serving.Input)
    UnsafeMergeFrom(*source);
  }
}

void Input::MergeFrom(const Input& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:tensorflow.serving.Input)
  if (GOOGLE_PREDICT_TRUE(&from != this)) {
    UnsafeMergeFrom(from);
  } else {
    MergeFromFail(__LINE__);
  }
}

void Input::UnsafeMergeFrom(const Input& from) {
  GOOGLE_DCHECK(&from != this);
  switch (from.kind_case()) {
    case kExampleList: {
      mutable_example_list()->::tensorflow::serving::ExampleList::MergeFrom(from.example_list());
      break;
    }
    case kExampleListWithContext: {
      mutable_example_list_with_context()->::tensorflow::serving::ExampleListWithContext::MergeFrom(from.example_list_with_context());
      break;
    }
    case KIND_NOT_SET: {
      break;
    }
  }
}

void Input::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:tensorflow.serving.Input)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Input::CopyFrom(const Input& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:tensorflow.serving.Input)
  if (&from == this) return;
  Clear();
  UnsafeMergeFrom(from);
}

bool Input::IsInitialized() const {

  return true;
}

void Input::Swap(Input* other) {
  if (other == this) return;
  if (GetArenaNoVirtual() == other->GetArenaNoVirtual()) {
    InternalSwap(other);
  } else {
    Input temp;
    temp.UnsafeMergeFrom(*this);
    CopyFrom(*other);
    other->CopyFrom(temp);
  }
}
void Input::UnsafeArenaSwap(Input* other) {
  if (other == this) return;
  GOOGLE_DCHECK(GetArenaNoVirtual() == other->GetArenaNoVirtual());
  InternalSwap(other);
}
void Input::InternalSwap(Input* other) {
  std::swap(kind_, other->kind_);
  std::swap(_oneof_case_[0], other->_oneof_case_[0]);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Input::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Input_descriptor_;
  metadata.reflection = Input_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Input

// optional .tensorflow.serving.ExampleList example_list = 1;
bool Input::has_example_list() const {
  return kind_case() == kExampleList;
}
void Input::set_has_example_list() {
  _oneof_case_[0] = kExampleList;
}
void Input::clear_example_list() {
  if (has_example_list()) {
    if (GetArenaNoVirtual() == NULL) {
      delete kind_.example_list_;
    }
    clear_has_kind();
  }
}
 const ::tensorflow::serving::ExampleList& Input::example_list() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.Input.example_list)
  return has_example_list()
      ? *kind_.example_list_
      : ::tensorflow::serving::ExampleList::default_instance();
}
::tensorflow::serving::ExampleList* Input::mutable_example_list() {
  if (!has_example_list()) {
    clear_kind();
    set_has_example_list();
    kind_.example_list_ = 
      ::google::protobuf::Arena::CreateMessage< ::tensorflow::serving::ExampleList >(
      GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.Input.example_list)
  return kind_.example_list_;
}
::tensorflow::serving::ExampleList* Input::release_example_list() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.Input.example_list)
  if (has_example_list()) {
    clear_has_kind();
    if (GetArenaNoVirtual() != NULL) {
      ::tensorflow::serving::ExampleList* temp = new ::tensorflow::serving::ExampleList(*kind_.example_list_);
      kind_.example_list_ = NULL;
      return temp;
    } else {
      ::tensorflow::serving::ExampleList* temp = kind_.example_list_;
      kind_.example_list_ = NULL;
      return temp;
    }
  } else {
    return NULL;
  }
}
void Input::set_allocated_example_list(::tensorflow::serving::ExampleList* example_list) {
  clear_kind();
  if (example_list) {
    if (GetArenaNoVirtual() != NULL &&
        ::google::protobuf::Arena::GetArena(example_list) == NULL) {
      GetArenaNoVirtual()->Own(example_list);
    } else if (GetArenaNoVirtual() !=
               ::google::protobuf::Arena::GetArena(example_list)) {
      ::tensorflow::serving::ExampleList* new_example_list = 
          ::google::protobuf::Arena::CreateMessage< ::tensorflow::serving::ExampleList >(
          GetArenaNoVirtual());
      new_example_list->CopyFrom(*example_list);
      example_list = new_example_list;
    }
    set_has_example_list();
    kind_.example_list_ = example_list;
  }
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.Input.example_list)
}
 ::tensorflow::serving::ExampleList* Input::unsafe_arena_release_example_list() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tensorflow.serving.Input.example_list)
  if (has_example_list()) {
    clear_has_kind();
    ::tensorflow::serving::ExampleList* temp = kind_.example_list_;
    kind_.example_list_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
 void Input::unsafe_arena_set_allocated_example_list(::tensorflow::serving::ExampleList* example_list) {
  clear_kind();
  if (example_list) {
    set_has_example_list();
    kind_.example_list_ = example_list;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.Input.example_list)
}

// optional .tensorflow.serving.ExampleListWithContext example_list_with_context = 2;
bool Input::has_example_list_with_context() const {
  return kind_case() == kExampleListWithContext;
}
void Input::set_has_example_list_with_context() {
  _oneof_case_[0] = kExampleListWithContext;
}
void Input::clear_example_list_with_context() {
  if (has_example_list_with_context()) {
    if (GetArenaNoVirtual() == NULL) {
      delete kind_.example_list_with_context_;
    }
    clear_has_kind();
  }
}
 const ::tensorflow::serving::ExampleListWithContext& Input::example_list_with_context() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.Input.example_list_with_context)
  return has_example_list_with_context()
      ? *kind_.example_list_with_context_
      : ::tensorflow::serving::ExampleListWithContext::default_instance();
}
::tensorflow::serving::ExampleListWithContext* Input::mutable_example_list_with_context() {
  if (!has_example_list_with_context()) {
    clear_kind();
    set_has_example_list_with_context();
    kind_.example_list_with_context_ = 
      ::google::protobuf::Arena::CreateMessage< ::tensorflow::serving::ExampleListWithContext >(
      GetArenaNoVirtual());
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.Input.example_list_with_context)
  return kind_.example_list_with_context_;
}
::tensorflow::serving::ExampleListWithContext* Input::release_example_list_with_context() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.Input.example_list_with_context)
  if (has_example_list_with_context()) {
    clear_has_kind();
    if (GetArenaNoVirtual() != NULL) {
      ::tensorflow::serving::ExampleListWithContext* temp = new ::tensorflow::serving::ExampleListWithContext(*kind_.example_list_with_context_);
      kind_.example_list_with_context_ = NULL;
      return temp;
    } else {
      ::tensorflow::serving::ExampleListWithContext* temp = kind_.example_list_with_context_;
      kind_.example_list_with_context_ = NULL;
      return temp;
    }
  } else {
    return NULL;
  }
}
void Input::set_allocated_example_list_with_context(::tensorflow::serving::ExampleListWithContext* example_list_with_context) {
  clear_kind();
  if (example_list_with_context) {
    if (GetArenaNoVirtual() != NULL &&
        ::google::protobuf::Arena::GetArena(example_list_with_context) == NULL) {
      GetArenaNoVirtual()->Own(example_list_with_context);
    } else if (GetArenaNoVirtual() !=
               ::google::protobuf::Arena::GetArena(example_list_with_context)) {
      ::tensorflow::serving::ExampleListWithContext* new_example_list_with_context = 
          ::google::protobuf::Arena::CreateMessage< ::tensorflow::serving::ExampleListWithContext >(
          GetArenaNoVirtual());
      new_example_list_with_context->CopyFrom(*example_list_with_context);
      example_list_with_context = new_example_list_with_context;
    }
    set_has_example_list_with_context();
    kind_.example_list_with_context_ = example_list_with_context;
  }
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.Input.example_list_with_context)
}
 ::tensorflow::serving::ExampleListWithContext* Input::unsafe_arena_release_example_list_with_context() {
  // @@protoc_insertion_point(field_unsafe_arena_release:tensorflow.serving.Input.example_list_with_context)
  if (has_example_list_with_context()) {
    clear_has_kind();
    ::tensorflow::serving::ExampleListWithContext* temp = kind_.example_list_with_context_;
    kind_.example_list_with_context_ = NULL;
    return temp;
  } else {
    return NULL;
  }
}
 void Input::unsafe_arena_set_allocated_example_list_with_context(::tensorflow::serving::ExampleListWithContext* example_list_with_context) {
  clear_kind();
  if (example_list_with_context) {
    set_has_example_list_with_context();
    kind_.example_list_with_context_ = example_list_with_context;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:tensorflow.serving.Input.example_list_with_context)
}

bool Input::has_kind() const {
  return kind_case() != KIND_NOT_SET;
}
void Input::clear_has_kind() {
  _oneof_case_[0] = KIND_NOT_SET;
}
Input::KindCase Input::kind_case() const {
  return Input::KindCase(_oneof_case_[0]);
}
inline const Input* Input::internal_default_instance() {
  return &Input_default_instance_.get();
}
#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

}  // namespace serving
}  // namespace tensorflow

// @@protoc_insertion_point(global_scope)
