// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: tensorflow_serving/apis/regression.proto

#ifndef PROTOBUF_tensorflow_5fserving_2fapis_2fregression_2eproto__INCLUDED
#define PROTOBUF_tensorflow_5fserving_2fapis_2fregression_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 3001000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 3001000 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/unknown_field_set.h>
#include "tensorflow_serving/apis/input.pb.h"
#include "tensorflow_serving/apis/model.pb.h"
// @@protoc_insertion_point(includes)

namespace tensorflow {
namespace serving {

// Internal implementation detail -- do not call these.
void protobuf_AddDesc_tensorflow_5fserving_2fapis_2fregression_2eproto();
void protobuf_InitDefaults_tensorflow_5fserving_2fapis_2fregression_2eproto();
void protobuf_AssignDesc_tensorflow_5fserving_2fapis_2fregression_2eproto();
void protobuf_ShutdownFile_tensorflow_5fserving_2fapis_2fregression_2eproto();

class Regression;
class RegressionRequest;
class RegressionResponse;
class RegressionResult;

// ===================================================================

class Regression : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.serving.Regression) */ {
 public:
  Regression();
  virtual ~Regression();

  Regression(const Regression& from);

  inline Regression& operator=(const Regression& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const Regression& default_instance();

  static const Regression* internal_default_instance();

  void UnsafeArenaSwap(Regression* other);
  void Swap(Regression* other);

  // implements Message ----------------------------------------------

  inline Regression* New() const { return New(NULL); }

  Regression* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const Regression& from);
  void MergeFrom(const Regression& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(Regression* other);
  void UnsafeMergeFrom(const Regression& from);
  protected:
  explicit Regression(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional float value = 1;
  void clear_value();
  static const int kValueFieldNumber = 1;
  float value() const;
  void set_value(float value);

  // @@protoc_insertion_point(class_scope:tensorflow.serving.Regression)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  float value_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_tensorflow_5fserving_2fapis_2fregression_2eproto_impl();
  friend void  protobuf_AddDesc_tensorflow_5fserving_2fapis_2fregression_2eproto_impl();
  friend void protobuf_AssignDesc_tensorflow_5fserving_2fapis_2fregression_2eproto();
  friend void protobuf_ShutdownFile_tensorflow_5fserving_2fapis_2fregression_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<Regression> Regression_default_instance_;

// -------------------------------------------------------------------

class RegressionResult : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.serving.RegressionResult) */ {
 public:
  RegressionResult();
  virtual ~RegressionResult();

  RegressionResult(const RegressionResult& from);

  inline RegressionResult& operator=(const RegressionResult& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const RegressionResult& default_instance();

  static const RegressionResult* internal_default_instance();

  void UnsafeArenaSwap(RegressionResult* other);
  void Swap(RegressionResult* other);

  // implements Message ----------------------------------------------

  inline RegressionResult* New() const { return New(NULL); }

  RegressionResult* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RegressionResult& from);
  void MergeFrom(const RegressionResult& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RegressionResult* other);
  void UnsafeMergeFrom(const RegressionResult& from);
  protected:
  explicit RegressionResult(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // repeated .tensorflow.serving.Regression regressions = 1;
  int regressions_size() const;
  void clear_regressions();
  static const int kRegressionsFieldNumber = 1;
  const ::tensorflow::serving::Regression& regressions(int index) const;
  ::tensorflow::serving::Regression* mutable_regressions(int index);
  ::tensorflow::serving::Regression* add_regressions();
  ::google::protobuf::RepeatedPtrField< ::tensorflow::serving::Regression >*
      mutable_regressions();
  const ::google::protobuf::RepeatedPtrField< ::tensorflow::serving::Regression >&
      regressions() const;

  // @@protoc_insertion_point(class_scope:tensorflow.serving.RegressionResult)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::google::protobuf::RepeatedPtrField< ::tensorflow::serving::Regression > regressions_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_tensorflow_5fserving_2fapis_2fregression_2eproto_impl();
  friend void  protobuf_AddDesc_tensorflow_5fserving_2fapis_2fregression_2eproto_impl();
  friend void protobuf_AssignDesc_tensorflow_5fserving_2fapis_2fregression_2eproto();
  friend void protobuf_ShutdownFile_tensorflow_5fserving_2fapis_2fregression_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<RegressionResult> RegressionResult_default_instance_;

// -------------------------------------------------------------------

class RegressionRequest : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.serving.RegressionRequest) */ {
 public:
  RegressionRequest();
  virtual ~RegressionRequest();

  RegressionRequest(const RegressionRequest& from);

  inline RegressionRequest& operator=(const RegressionRequest& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const RegressionRequest& default_instance();

  static const RegressionRequest* internal_default_instance();

  void UnsafeArenaSwap(RegressionRequest* other);
  void Swap(RegressionRequest* other);

  // implements Message ----------------------------------------------

  inline RegressionRequest* New() const { return New(NULL); }

  RegressionRequest* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RegressionRequest& from);
  void MergeFrom(const RegressionRequest& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RegressionRequest* other);
  void UnsafeMergeFrom(const RegressionRequest& from);
  protected:
  explicit RegressionRequest(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .tensorflow.serving.ModelSpec model_spec = 1;
  bool has_model_spec() const;
  void clear_model_spec();
  static const int kModelSpecFieldNumber = 1;
  private:
  void _slow_mutable_model_spec();
  void _slow_set_allocated_model_spec(
      ::google::protobuf::Arena* message_arena, ::tensorflow::serving::ModelSpec** model_spec);
  ::tensorflow::serving::ModelSpec* _slow_release_model_spec();
  public:
  const ::tensorflow::serving::ModelSpec& model_spec() const;
  ::tensorflow::serving::ModelSpec* mutable_model_spec();
  ::tensorflow::serving::ModelSpec* release_model_spec();
  void set_allocated_model_spec(::tensorflow::serving::ModelSpec* model_spec);
  ::tensorflow::serving::ModelSpec* unsafe_arena_release_model_spec();
  void unsafe_arena_set_allocated_model_spec(
      ::tensorflow::serving::ModelSpec* model_spec);

  // optional .tensorflow.serving.Input input = 2;
  bool has_input() const;
  void clear_input();
  static const int kInputFieldNumber = 2;
  private:
  void _slow_mutable_input();
  void _slow_set_allocated_input(
      ::google::protobuf::Arena* message_arena, ::tensorflow::serving::Input** input);
  ::tensorflow::serving::Input* _slow_release_input();
  public:
  const ::tensorflow::serving::Input& input() const;
  ::tensorflow::serving::Input* mutable_input();
  ::tensorflow::serving::Input* release_input();
  void set_allocated_input(::tensorflow::serving::Input* input);
  ::tensorflow::serving::Input* unsafe_arena_release_input();
  void unsafe_arena_set_allocated_input(
      ::tensorflow::serving::Input* input);

  // @@protoc_insertion_point(class_scope:tensorflow.serving.RegressionRequest)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::tensorflow::serving::ModelSpec* model_spec_;
  ::tensorflow::serving::Input* input_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_tensorflow_5fserving_2fapis_2fregression_2eproto_impl();
  friend void  protobuf_AddDesc_tensorflow_5fserving_2fapis_2fregression_2eproto_impl();
  friend void protobuf_AssignDesc_tensorflow_5fserving_2fapis_2fregression_2eproto();
  friend void protobuf_ShutdownFile_tensorflow_5fserving_2fapis_2fregression_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<RegressionRequest> RegressionRequest_default_instance_;

// -------------------------------------------------------------------

class RegressionResponse : public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:tensorflow.serving.RegressionResponse) */ {
 public:
  RegressionResponse();
  virtual ~RegressionResponse();

  RegressionResponse(const RegressionResponse& from);

  inline RegressionResponse& operator=(const RegressionResponse& from) {
    CopyFrom(from);
    return *this;
  }

  inline ::google::protobuf::Arena* GetArena() const { return GetArenaNoVirtual(); }
  inline void* GetMaybeArenaPointer() const {
    return MaybeArenaPtr();
  }
  static const ::google::protobuf::Descriptor* descriptor();
  static const RegressionResponse& default_instance();

  static const RegressionResponse* internal_default_instance();

  void UnsafeArenaSwap(RegressionResponse* other);
  void Swap(RegressionResponse* other);

  // implements Message ----------------------------------------------

  inline RegressionResponse* New() const { return New(NULL); }

  RegressionResponse* New(::google::protobuf::Arena* arena) const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RegressionResponse& from);
  void MergeFrom(const RegressionResponse& from);
  void Clear();
  bool IsInitialized() const;

  size_t ByteSizeLong() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* InternalSerializeWithCachedSizesToArray(
      bool deterministic, ::google::protobuf::uint8* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const {
    return InternalSerializeWithCachedSizesToArray(false, output);
  }
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  void InternalSwap(RegressionResponse* other);
  void UnsafeMergeFrom(const RegressionResponse& from);
  protected:
  explicit RegressionResponse(::google::protobuf::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::google::protobuf::Arena* arena);
  private:
  inline ::google::protobuf::Arena* GetArenaNoVirtual() const {
    return _internal_metadata_.arena();
  }
  inline void* MaybeArenaPtr() const {
    return _internal_metadata_.raw_arena_ptr();
  }
  public:

  ::google::protobuf::Metadata GetMetadata() const;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  // optional .tensorflow.serving.RegressionResult result = 1;
  bool has_result() const;
  void clear_result();
  static const int kResultFieldNumber = 1;
  private:
  void _slow_mutable_result();
  void _slow_set_allocated_result(
      ::google::protobuf::Arena* message_arena, ::tensorflow::serving::RegressionResult** result);
  ::tensorflow::serving::RegressionResult* _slow_release_result();
  public:
  const ::tensorflow::serving::RegressionResult& result() const;
  ::tensorflow::serving::RegressionResult* mutable_result();
  ::tensorflow::serving::RegressionResult* release_result();
  void set_allocated_result(::tensorflow::serving::RegressionResult* result);
  ::tensorflow::serving::RegressionResult* unsafe_arena_release_result();
  void unsafe_arena_set_allocated_result(
      ::tensorflow::serving::RegressionResult* result);

  // @@protoc_insertion_point(class_scope:tensorflow.serving.RegressionResponse)
 private:

  ::google::protobuf::internal::InternalMetadataWithArena _internal_metadata_;
  friend class ::google::protobuf::Arena;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::tensorflow::serving::RegressionResult* result_;
  mutable int _cached_size_;
  friend void  protobuf_InitDefaults_tensorflow_5fserving_2fapis_2fregression_2eproto_impl();
  friend void  protobuf_AddDesc_tensorflow_5fserving_2fapis_2fregression_2eproto_impl();
  friend void protobuf_AssignDesc_tensorflow_5fserving_2fapis_2fregression_2eproto();
  friend void protobuf_ShutdownFile_tensorflow_5fserving_2fapis_2fregression_2eproto();

  void InitAsDefaultInstance();
};
extern ::google::protobuf::internal::ExplicitlyConstructed<RegressionResponse> RegressionResponse_default_instance_;

// ===================================================================


// ===================================================================

#if !PROTOBUF_INLINE_NOT_IN_HEADERS
// Regression

// optional float value = 1;
inline void Regression::clear_value() {
  value_ = 0;
}
inline float Regression::value() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.Regression.value)
  return value_;
}
inline void Regression::set_value(float value) {
  
  value_ = value;
  // @@protoc_insertion_point(field_set:tensorflow.serving.Regression.value)
}

inline const Regression* Regression::internal_default_instance() {
  return &Regression_default_instance_.get();
}
// -------------------------------------------------------------------

// RegressionResult

// repeated .tensorflow.serving.Regression regressions = 1;
inline int RegressionResult::regressions_size() const {
  return regressions_.size();
}
inline void RegressionResult::clear_regressions() {
  regressions_.Clear();
}
inline const ::tensorflow::serving::Regression& RegressionResult::regressions(int index) const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.RegressionResult.regressions)
  return regressions_.Get(index);
}
inline ::tensorflow::serving::Regression* RegressionResult::mutable_regressions(int index) {
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.RegressionResult.regressions)
  return regressions_.Mutable(index);
}
inline ::tensorflow::serving::Regression* RegressionResult::add_regressions() {
  // @@protoc_insertion_point(field_add:tensorflow.serving.RegressionResult.regressions)
  return regressions_.Add();
}
inline ::google::protobuf::RepeatedPtrField< ::tensorflow::serving::Regression >*
RegressionResult::mutable_regressions() {
  // @@protoc_insertion_point(field_mutable_list:tensorflow.serving.RegressionResult.regressions)
  return &regressions_;
}
inline const ::google::protobuf::RepeatedPtrField< ::tensorflow::serving::Regression >&
RegressionResult::regressions() const {
  // @@protoc_insertion_point(field_list:tensorflow.serving.RegressionResult.regressions)
  return regressions_;
}

inline const RegressionResult* RegressionResult::internal_default_instance() {
  return &RegressionResult_default_instance_.get();
}
// -------------------------------------------------------------------

// RegressionRequest

// optional .tensorflow.serving.ModelSpec model_spec = 1;
inline bool RegressionRequest::has_model_spec() const {
  return this != internal_default_instance() && model_spec_ != NULL;
}
inline void RegressionRequest::clear_model_spec() {
  if (GetArenaNoVirtual() == NULL && model_spec_ != NULL) delete model_spec_;
  model_spec_ = NULL;
}
inline const ::tensorflow::serving::ModelSpec& RegressionRequest::model_spec() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.RegressionRequest.model_spec)
  return model_spec_ != NULL ? *model_spec_
                         : *::tensorflow::serving::ModelSpec::internal_default_instance();
}
inline ::tensorflow::serving::ModelSpec* RegressionRequest::mutable_model_spec() {
  
  if (model_spec_ == NULL) {
    _slow_mutable_model_spec();
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.RegressionRequest.model_spec)
  return model_spec_;
}
inline ::tensorflow::serving::ModelSpec* RegressionRequest::release_model_spec() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.RegressionRequest.model_spec)
  
  if (GetArenaNoVirtual() != NULL) {
    return _slow_release_model_spec();
  } else {
    ::tensorflow::serving::ModelSpec* temp = model_spec_;
    model_spec_ = NULL;
    return temp;
  }
}
inline  void RegressionRequest::set_allocated_model_spec(::tensorflow::serving::ModelSpec* model_spec) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete model_spec_;
  }
  if (model_spec != NULL) {
    _slow_set_allocated_model_spec(message_arena, &model_spec);
  }
  model_spec_ = model_spec;
  if (model_spec) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.RegressionRequest.model_spec)
}

// optional .tensorflow.serving.Input input = 2;
inline bool RegressionRequest::has_input() const {
  return this != internal_default_instance() && input_ != NULL;
}
inline void RegressionRequest::clear_input() {
  if (GetArenaNoVirtual() == NULL && input_ != NULL) delete input_;
  input_ = NULL;
}
inline const ::tensorflow::serving::Input& RegressionRequest::input() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.RegressionRequest.input)
  return input_ != NULL ? *input_
                         : *::tensorflow::serving::Input::internal_default_instance();
}
inline ::tensorflow::serving::Input* RegressionRequest::mutable_input() {
  
  if (input_ == NULL) {
    _slow_mutable_input();
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.RegressionRequest.input)
  return input_;
}
inline ::tensorflow::serving::Input* RegressionRequest::release_input() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.RegressionRequest.input)
  
  if (GetArenaNoVirtual() != NULL) {
    return _slow_release_input();
  } else {
    ::tensorflow::serving::Input* temp = input_;
    input_ = NULL;
    return temp;
  }
}
inline  void RegressionRequest::set_allocated_input(::tensorflow::serving::Input* input) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete input_;
  }
  if (input != NULL) {
    _slow_set_allocated_input(message_arena, &input);
  }
  input_ = input;
  if (input) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.RegressionRequest.input)
}

inline const RegressionRequest* RegressionRequest::internal_default_instance() {
  return &RegressionRequest_default_instance_.get();
}
// -------------------------------------------------------------------

// RegressionResponse

// optional .tensorflow.serving.RegressionResult result = 1;
inline bool RegressionResponse::has_result() const {
  return this != internal_default_instance() && result_ != NULL;
}
inline void RegressionResponse::clear_result() {
  if (GetArenaNoVirtual() == NULL && result_ != NULL) delete result_;
  result_ = NULL;
}
inline const ::tensorflow::serving::RegressionResult& RegressionResponse::result() const {
  // @@protoc_insertion_point(field_get:tensorflow.serving.RegressionResponse.result)
  return result_ != NULL ? *result_
                         : *::tensorflow::serving::RegressionResult::internal_default_instance();
}
inline ::tensorflow::serving::RegressionResult* RegressionResponse::mutable_result() {
  
  if (result_ == NULL) {
    _slow_mutable_result();
  }
  // @@protoc_insertion_point(field_mutable:tensorflow.serving.RegressionResponse.result)
  return result_;
}
inline ::tensorflow::serving::RegressionResult* RegressionResponse::release_result() {
  // @@protoc_insertion_point(field_release:tensorflow.serving.RegressionResponse.result)
  
  if (GetArenaNoVirtual() != NULL) {
    return _slow_release_result();
  } else {
    ::tensorflow::serving::RegressionResult* temp = result_;
    result_ = NULL;
    return temp;
  }
}
inline  void RegressionResponse::set_allocated_result(::tensorflow::serving::RegressionResult* result) {
  ::google::protobuf::Arena* message_arena = GetArenaNoVirtual();
  if (message_arena == NULL) {
    delete result_;
  }
  if (result != NULL) {
    _slow_set_allocated_result(message_arena, &result);
  }
  result_ = result;
  if (result) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_set_allocated:tensorflow.serving.RegressionResponse.result)
}

inline const RegressionResponse* RegressionResponse::internal_default_instance() {
  return &RegressionResponse_default_instance_.get();
}
#endif  // !PROTOBUF_INLINE_NOT_IN_HEADERS
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace serving
}  // namespace tensorflow

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_tensorflow_5fserving_2fapis_2fregression_2eproto__INCLUDED
